Additional getComponentConstructor() condition
I've accidentally come across such error:
> TypeError: Component.bind is not a function

I don't know how it actually happened but seems this condition is not cover all cases:

```
// if not from Ractive.extend or a Promise, it's a function that should return a constructor
if ( Component && !Component.isInstance && !Component.then ) {
...
}
```
I think the logic here is not insufficient and we also need to check Component variable type, because if it' not an instance or promise it doesn't mean that it's a function.